export const GET_BUSINESSES = 'GET_BUSINESSES';
export const GET_IMPORTANT_TO_BUSINESS = 'GET_IMPORTANT_TO_BUSINESS ';
export const BUSINESS_ERROR = 'BUSINESS_ERROR';

export const GET_CONTACTS = 'GET_CONTACTS';
export const CONTACT_ERROR = 'CONTACT_ERROR';

export const GET_INDUSTRIES = 'GET_INDUSTRIES';
export const INDUSTRY_ERROR = 'INDUSTRY_ERROR';

export const GET_SERVICES = 'GET_SERVICES';
export const SERVICE_ERROR = 'SERVICE_ERROR';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
