export const RESET_BUSINESSES = 'RESET_BUSINESSES';
export const GET_BUSINESSES = 'GET_BUSINESSES';
export const GET_EVENT_ATTENDANCE = 'GET_EVENT_ATTENDANCE';
export const GET_IMPORTANT_TO_BUSINESS = 'GET_IMPORTANT_TO_BUSINESS ';
export const BUSINESS_ERROR = 'BUSINESS_ERROR';

export const GET_CONTACTS = 'GET_CONTACTS';
export const CONTACT_ERROR = 'CONTACT_ERROR';

export const GET_NOTES = 'GET_NOTES';
export const COUNT_NOTES = 'COUNT_NOTES';
export const CREATE_NOTE = 'CREATE_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const NOTE_ERROR = 'NOTE_ERROR';

export const GET_EVENTS = 'GET_EVENTS';
export const GET_ATTANDANCE_AT_EVENT = 'GET_ATTANDANCE_AT_EVENT';
export const CREATE_EVENT = 'CREATE_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const DELETE_ATTENDANCE_TO_EVENT = 'DELETE_ATTENDANCE_TO_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const EVENT_ERROR = 'EVENT_ERROR';

export const GET_EVENT_SPECIALS = 'GET_EVENT_SPECIALS';
export const CREATE_EVENT_SPECIAL = 'CREATE_EVENT_SPECIAL';
export const UPDATE_EVENT_SPECIAL = 'UPDATE_EVENT_SPECIAL';
export const DELETE_EVENT_SPECIAL = 'DELETE_EVENT_SPECIAL';
export const EVENT_SPECIAL_ERROR = 'EVENT_SPECIAL_ERROR';

export const GET_INDUSTRIES = 'GET_INDUSTRIES';
export const INDUSTRY_ERROR = 'INDUSTRY_ERROR';

export const GET_SERVICES = 'GET_SERVICES';
export const SERVICE_ERROR = 'SERVICE_ERROR';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
